# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default
  vmImage: Default

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(941814d0-69c2-4061-bb77-a5872f73b7f6)'
    azureContainerRegistry: '{"loginServer":"amoltestcontainers.azurecr.io", "id" : "/subscriptions/941814d0-69c2-4061-bb77-a5872f73b7f6/resourceGroups/docker01_group/providers/Microsoft.ContainerRegistry/registries/amoltestcontainers"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'