version: "3.9"
services:
  my-jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    
  
    ports:
      - "9998:8080"
      - "9999:8443"

    volumes:
      - ./logs/:/usr/local/tomcat/logs


    container_name: jenkinstomcat02